# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Fantazia')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=255, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('website', models.CharField(max_length=255, verbose_name='Website')),
                ('linkedin', models.CharField(max_length=255, verbose_name='LinkedIN')),
            ],
        ),
    ]
