# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='beneficios',
            field=models.TextField(null=True, verbose_name='Benefícios'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='localidade',
            field=models.TextField(verbose_name='Localidade'),
        ),
    ]
