# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='linkedin',
            field=models.CharField(max_length=255, null=True, verbose_name='LinkedIN'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='website',
            field=models.CharField(max_length=255, null=True, verbose_name='Website'),
        ),
    ]
