# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_areaatuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da vaga')),
                ('resumo', models.TextField(verbose_name='Resumo da vaga')),
                ('localidade', models.TextField(verbose_name='Resumo da vaga')),
                ('salario', models.CharField(max_length=255, verbose_name='Salário')),
                ('beneficios', models.CharField(max_length=255, null=True, verbose_name='Benefícios')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição completa')),
                ('area_atuacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AreaAtuacao', verbose_name='Área de Atuação')),
            ],
        ),
    ]
