# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('status', models.CharField(choices=[('AN', 'Em análise'), ('AC', 'Aceito'), ('RE', 'Recusado')], max_length=2, verbose_name='Status')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vaga', verbose_name='Vaga')),
            ],
        ),
    ]
