# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('celular', models.CharField(max_length=30, verbose_name='Celular')),
                ('linkedin', models.CharField(max_length=255, verbose_name='LinkedIN')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('curriculo', models.FileField(upload_to='', verbose_name='Currículo')),
                ('analise_recrutador', models.TextField(verbose_name='Análise Recrutador')),
                ('area_atuacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AreaAtuacao', verbose_name='Área de Atuação')),
            ],
            options={
                'abstract': False,
            },
            bases=('contas.usuario',),
        ),
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skype', models.CharField(max_length=255, verbose_name='Skype')),
                ('email_profissional', models.EmailField(max_length=254, null=True, verbose_name='Email Profissional')),
                ('telefone_empresarial', models.CharField(max_length=255, null=True, verbose_name='Telefone Empresarial')),
                ('cargo', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
            ],
            options={
                'abstract': False,
            },
            bases=('contas.usuario',),
        ),
        migrations.CreateModel(
            name='Recrutador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_recrutador', models.CharField(choices=[('MA', 'Recrutador Master'), ('RE', 'Recrutador')], default='RE', max_length=2)),
                ('skype', models.CharField(max_length=255, verbose_name='Skype')),
                ('telefone', models.CharField(max_length=255, null=True, verbose_name='Telefone')),
                ('area_atuacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AreaAtuacao', verbose_name='Área de Atuação')),
            ],
            options={
                'abstract': False,
            },
            bases=('contas.usuario',),
        ),
    ]
