# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20160828_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('SE', 'Recrutador Senior'), ('MA', 'Recrutador Master'), ('RE', 'Recrutador'), ('CA', 'Candidato'), ('CO', 'Contratante')], max_length=2)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=30, verbose_name='Celular')),
                ('skype', models.CharField(max_length=255, verbose_name='Skype')),
                ('linkedin', models.CharField(max_length=255, verbose_name='LinkedIN')),
                ('email_profissional', models.EmailField(max_length=254, null=True, verbose_name='Email Profissional')),
                ('telefone_empresarial', models.CharField(max_length=255, null=True, verbose_name='Telefone Empresarial')),
                ('cargo', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
