# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20160828_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='recrutador',
            name='tipo_recrutador',
            field=models.CharField(choices=[('SE', 'Recrutador Senior'), ('MA', 'Recrutador Master'), ('RE', 'Recrutador')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tipo',
            field=models.CharField(choices=[('RE', 'Recrutador'), ('CA', 'Candidato'), ('CO', 'Contratante')], max_length=2),
        ),
        migrations.AlterField(
            model_name='contratante',
            name='tipo',
            field=models.CharField(choices=[('RE', 'Recrutador'), ('CA', 'Candidato'), ('CO', 'Contratante')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recrutador',
            name='tipo',
            field=models.CharField(choices=[('RE', 'Recrutador'), ('CA', 'Candidato'), ('CO', 'Contratante')], max_length=2),
        ),
    ]
